

#服务端口
server:
    port: 8989

#默认使用配置
spring:
    profiles:
        active: dev

#公共配置与profiles选择无关
mybatis:
    typeAliasesPackage: com.demo.model
    mapperLocations: classpath:mapping/*.xml


---
#开发配置
spring:
    profiles: dev
    #数据源(alibaba druid)
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: Txc961213
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    #thymeleaf
    thymeleaf:
        prefix: classpath:/templates/
        cache: false
        suffix: .html
    #mvc
    mvc:
        static-path-pattern: /static/**